services:
  - type: web
    name: stock-sense
    env: python
    plan: free
    buildCommand: ""
    startCommand: streamlit run app.py --server.port=10000 --server.enableCORS=false
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
